version: '3'
services:
  service:
    restart: always
    build: .
    ports:
      - 80:3001
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: